server:
  port: 8001
spring:
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.91.141.30:3306/goods_example?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: Micahmysqlmima123.
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name:
  #出现错误时, 直接抛出异常  处理404
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 自增
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDel
# token的标识
tokenMark: Authorization


